import type {
  Call,
  Client,
  Framework,
  FrameworkTemplate,
  IntegrationApiKey,
  WebhookSubscription,
  WebhookEvent,
  JobAttempt,
  Organization,
  OrgCapabilities,
  StorageUsage,
} from "./types"

// ==================== MOCK CALLS ====================

export const mockCalls: Call[] = [
  {
    id: "call-1",
    title: "Discovery Call - Acme Corp",
    clientId: "client-1",
    clientName: "Acme Corporation",
    platform: "zoom",
    scheduledAt: "2024-01-15T10:00:00Z",
    startedAt: "2024-01-15T10:02:00Z",
    endedAt: "2024-01-15T10:47:00Z",
    duration: 2700,
    status: "ready",
    participants: [
      { id: "p1", name: "John Smith", email: "john@company.com", role: "rep", speakerLabel: "Speaker 1" },
      { id: "p2", name: "Sarah Johnson", email: "sarah@acme.com", role: "prospect", speakerLabel: "Speaker 2" },
      { id: "p3", name: "Mike Chen", email: "mike@acme.com", role: "prospect", speakerLabel: "Speaker 3" },
    ],
    mediaAssets: [
      {
        id: "asset-1",
        type: "video_mixed",
        bucket: "recordings",
        path: "calls/call-1/video.mp4",
        size: 125000000,
        mimeType: "video/mp4",
        status: "verified",
        verifiedAt: "2024-01-15T11:00:00Z",
        recallDeletedAt: "2024-01-15T11:05:00Z",
        createdAt: "2024-01-15T10:50:00Z",
        updatedAt: "2024-01-15T11:05:00Z",
      },
      {
        id: "asset-2",
        type: "transcript",
        bucket: "recordings",
        path: "calls/call-1/transcript.json",
        size: 45000,
        mimeType: "application/json",
        status: "verified",
        verifiedAt: "2024-01-15T10:55:00Z",
        recallDeletedAt: null,
        createdAt: "2024-01-15T10:50:00Z",
        updatedAt: "2024-01-15T10:55:00Z",
      },
    ],
    summary: {
      id: "sum-1",
      overview:
        "Productive discovery call with Acme Corp. The prospect showed strong interest in our enterprise solution, particularly the automation features. Budget discussions indicate Q2 decision timeline.",
      keyPoints: [
        "Current pain point: manual data entry taking 20+ hours/week",
        "Looking to reduce operational costs by 30%",
        "Decision maker is the VP of Operations (not on call)",
        "Competitor evaluation includes Salesforce and HubSpot",
      ],
      nextSteps: [
        "Schedule follow-up demo with VP of Operations",
        "Send ROI calculator spreadsheet",
        "Prepare custom pricing proposal",
      ],
      sentiment: "positive",
    },
    actionItems: [
      {
        id: "ai-1",
        text: "Send ROI calculator to Sarah",
        completed: false,
        assignee: "John Smith",
        dueDate: "2024-01-17",
      },
      {
        id: "ai-2",
        text: "Schedule demo with VP Operations",
        completed: false,
        assignee: "John Smith",
        dueDate: "2024-01-20",
      },
      { id: "ai-3", text: "Prepare custom pricing proposal", completed: true, assignee: "John Smith" },
    ],
    frameworkScore: {
      frameworkId: "fw-1",
      frameworkName: "MEDDIC",
      versionId: "fwv-1",
      overallScore: 78,
      phaseScores: [
        { phaseId: "ph-1", phaseName: "Metrics", score: 90, coveredQuestions: 4, totalQuestions: 4 },
        { phaseId: "ph-2", phaseName: "Economic Buyer", score: 60, coveredQuestions: 2, totalQuestions: 4 },
        { phaseId: "ph-3", phaseName: "Decision Criteria", score: 85, coveredQuestions: 3, totalQuestions: 4 },
        { phaseId: "ph-4", phaseName: "Decision Process", score: 70, coveredQuestions: 3, totalQuestions: 5 },
        { phaseId: "ph-5", phaseName: "Identify Pain", score: 95, coveredQuestions: 4, totalQuestions: 4 },
        { phaseId: "ph-6", phaseName: "Champion", score: 65, coveredQuestions: 2, totalQuestions: 3 },
      ],
      missedQuestions: [
        {
          phaseId: "ph-2",
          phaseName: "Economic Buyer",
          questionId: "q-1",
          questionText: "Who has final budget approval?",
        },
        { phaseId: "ph-2", phaseName: "Economic Buyer", questionId: "q-2", questionText: "What is the budget range?" },
        {
          phaseId: "ph-6",
          phaseName: "Champion",
          questionId: "q-3",
          questionText: "Who will advocate internally for us?",
        },
      ],
      coachingPlan: {
        nextCallAgenda: [
          "Confirm meeting with VP of Operations",
          "Deep dive into budget approval process",
          "Identify internal champion",
        ],
        questionsToAsk: [
          "Who has final sign-off on purchases over $50k?",
          "Is there anyone else on your team who has been pushing for this solution?",
          "What would make you a hero internally if this project succeeds?",
        ],
      },
    },
    archivalSteps: [
      { id: "as-1", step: "recall_complete", status: "completed", timestamp: "2024-01-15T10:48:00Z" },
      { id: "as-2", step: "download_started", status: "completed", timestamp: "2024-01-15T10:49:00Z" },
      { id: "as-3", step: "download_complete", status: "completed", timestamp: "2024-01-15T10:52:00Z" },
      { id: "as-4", step: "upload_complete", status: "completed", timestamp: "2024-01-15T10:55:00Z" },
      { id: "as-5", step: "verified", status: "completed", timestamp: "2024-01-15T11:00:00Z" },
      { id: "as-6", step: "recall_deleted", status: "completed", timestamp: "2024-01-15T11:05:00Z" },
    ],
    recallBotId: "bot-abc123",
    createdAt: "2024-01-14T15:00:00Z",
    updatedAt: "2024-01-15T11:05:00Z",
  },
  {
    id: "call-2",
    title: "Product Demo - TechStart Inc",
    clientId: "client-2",
    clientName: "TechStart Inc",
    platform: "google_meet",
    scheduledAt: "2024-01-16T14:00:00Z",
    startedAt: "2024-01-16T14:05:00Z",
    endedAt: "2024-01-16T14:55:00Z",
    duration: 3000,
    status: "processing",
    participants: [
      { id: "p4", name: "John Smith", role: "rep", speakerLabel: "Speaker 1" },
      { id: "p5", name: "Emily Davis", role: "prospect", speakerLabel: "Speaker 2" },
    ],
    mediaAssets: [
      {
        id: "asset-3",
        type: "video_mixed",
        bucket: "recordings",
        path: "calls/call-2/video.mp4",
        size: 150000000,
        mimeType: "video/mp4",
        status: "downloading",
        verifiedAt: null,
        recallDeletedAt: null,
        createdAt: "2024-01-16T15:00:00Z",
        updatedAt: "2024-01-16T15:00:00Z",
      },
    ],
    actionItems: [],
    archivalSteps: [
      { id: "as-7", step: "recall_complete", status: "completed", timestamp: "2024-01-16T14:56:00Z" },
      { id: "as-8", step: "download_started", status: "in_progress", timestamp: "2024-01-16T15:00:00Z" },
      { id: "as-9", step: "download_complete", status: "pending", timestamp: null },
      { id: "as-10", step: "upload_complete", status: "pending", timestamp: null },
      { id: "as-11", step: "verified", status: "pending", timestamp: null },
      { id: "as-12", step: "recall_deleted", status: "pending", timestamp: null },
    ],
    recallBotId: "bot-def456",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-16T15:00:00Z",
  },
  {
    id: "call-3",
    title: "Quarterly Review - GlobalTech",
    clientId: "client-3",
    clientName: "GlobalTech Solutions",
    platform: "teams",
    scheduledAt: "2024-01-17T09:00:00Z",
    status: "scheduled",
    participants: [{ id: "p6", name: "John Smith", role: "rep", speakerLabel: "Speaker 1" }],
    mediaAssets: [],
    actionItems: [],
    archivalSteps: [],
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-01-10T08:00:00Z",
  },
  {
    id: "call-4",
    title: "Onboarding Call - StartupXYZ",
    clientId: "client-4",
    clientName: "StartupXYZ",
    platform: "zoom",
    scheduledAt: "2024-01-14T11:00:00Z",
    startedAt: "2024-01-14T11:00:00Z",
    endedAt: "2024-01-14T11:45:00Z",
    duration: 2700,
    status: "failed",
    participants: [
      { id: "p7", name: "John Smith", role: "rep", speakerLabel: "Speaker 1" },
      { id: "p8", name: "Alex Wong", role: "prospect", speakerLabel: "Speaker 2" },
    ],
    mediaAssets: [
      {
        id: "asset-4",
        type: "video_mixed",
        bucket: "recordings",
        path: "calls/call-4/video.mp4",
        size: 0,
        mimeType: "video/mp4",
        status: "failed",
        verifiedAt: null,
        recallDeletedAt: null,
        createdAt: "2024-01-14T11:50:00Z",
        updatedAt: "2024-01-14T12:00:00Z",
      },
    ],
    actionItems: [],
    archivalSteps: [
      { id: "as-13", step: "recall_complete", status: "completed", timestamp: "2024-01-14T11:46:00Z" },
      { id: "as-14", step: "download_started", status: "completed", timestamp: "2024-01-14T11:47:00Z" },
      {
        id: "as-15",
        step: "download_complete",
        status: "failed",
        timestamp: "2024-01-14T11:50:00Z",
        error: "Bot was not admitted to meeting",
      },
    ],
    recallBotId: "bot-ghi789",
    createdAt: "2024-01-13T09:00:00Z",
    updatedAt: "2024-01-14T12:00:00Z",
  },
  {
    id: "call-5",
    title: "Negotiation Call - Enterprise Ltd",
    clientId: "client-5",
    clientName: "Enterprise Ltd",
    platform: "zoom",
    scheduledAt: "2024-01-15T15:00:00Z",
    startedAt: "2024-01-15T15:00:00Z",
    status: "in_progress",
    participants: [
      { id: "p9", name: "John Smith", role: "rep", speakerLabel: "Speaker 1" },
      { id: "p10", name: "Patricia Miller", role: "prospect", speakerLabel: "Speaker 2" },
    ],
    mediaAssets: [],
    actionItems: [],
    archivalSteps: [],
    recallBotId: "bot-jkl012",
    createdAt: "2024-01-14T12:00:00Z",
    updatedAt: "2024-01-15T15:00:00Z",
  },
]

export const mockTranscript = [
  {
    id: "ts-1",
    speakerLabel: "Speaker 1",
    speakerRole: "rep" as const,
    speakerName: "John Smith",
    startMs: 0,
    endMs: 15000,
    text: "Hi Sarah, thanks for taking the time to meet today. I know you mentioned you were dealing with some challenges around data entry. Can you tell me more about that?",
  },
  {
    id: "ts-2",
    speakerLabel: "Speaker 2",
    speakerRole: "prospect" as const,
    speakerName: "Sarah Johnson",
    startMs: 16000,
    endMs: 45000,
    text: "Yes, absolutely. Right now our team spends about 20 hours a week just doing manual data entry. It's really eating into our productivity and honestly, it's demotivating for the team.",
    isHighlight: true,
    highlightType: "pain_point" as const,
  },
  {
    id: "ts-3",
    speakerLabel: "Speaker 1",
    speakerRole: "rep" as const,
    speakerName: "John Smith",
    startMs: 46000,
    endMs: 65000,
    text: "20 hours a week is significant. What would it mean for your business if you could reduce that by, say, 80%?",
  },
  {
    id: "ts-4",
    speakerLabel: "Speaker 2",
    speakerRole: "prospect" as const,
    speakerName: "Sarah Johnson",
    startMs: 66000,
    endMs: 95000,
    text: "That would be huge. We could reallocate those resources to actually growing the business instead of just maintaining it. We're looking to reduce operational costs by about 30% this year.",
    isHighlight: true,
    highlightType: "commitment" as const,
  },
  {
    id: "ts-5",
    speakerLabel: "Speaker 3",
    speakerRole: "prospect" as const,
    speakerName: "Mike Chen",
    startMs: 96000,
    endMs: 120000,
    text: "I have a question though. We've looked at Salesforce and HubSpot, and they seem to have similar automation features. What makes your solution different?",
    isHighlight: true,
    highlightType: "objection" as const,
  },
  {
    id: "ts-6",
    speakerLabel: "Speaker 1",
    speakerRole: "rep" as const,
    speakerName: "John Smith",
    startMs: 121000,
    endMs: 160000,
    text: "Great question, Mike. The key difference is our AI-powered workflow automation. While those platforms require you to manually set up every automation rule, our system learns from your team's patterns and suggests automations proactively.",
  },
]

// ==================== MOCK CLIENTS ====================

export const mockClients: Client[] = [
  {
    id: "client-1",
    name: "Acme Corporation",
    company: "Acme Corp",
    email: "contact@acme.com",
    phone: "+1 555-0100",
    externalRefs: ["sf-001234", "hs-789"],
    totalCalls: 5,
    lastCallAt: "2024-01-15T10:00:00Z",
    createdAt: "2023-10-01T00:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "client-2",
    name: "TechStart Inc",
    company: "TechStart",
    email: "hello@techstart.io",
    externalRefs: ["sf-005678"],
    totalCalls: 3,
    lastCallAt: "2024-01-16T14:00:00Z",
    createdAt: "2023-11-15T00:00:00Z",
    updatedAt: "2024-01-16T14:00:00Z",
  },
  {
    id: "client-3",
    name: "GlobalTech Solutions",
    company: "GlobalTech",
    email: "info@globaltech.com",
    phone: "+1 555-0200",
    externalRefs: [],
    totalCalls: 8,
    lastCallAt: "2024-01-10T09:00:00Z",
    createdAt: "2023-06-01T00:00:00Z",
    updatedAt: "2024-01-10T09:00:00Z",
  },
  {
    id: "client-4",
    name: "StartupXYZ",
    company: "StartupXYZ",
    email: "founders@startupxyz.com",
    externalRefs: ["hs-456"],
    totalCalls: 1,
    lastCallAt: "2024-01-14T11:00:00Z",
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-01-14T11:00:00Z",
  },
  {
    id: "client-5",
    name: "Enterprise Ltd",
    company: "Enterprise Ltd",
    email: "procurement@enterprise.com",
    phone: "+1 555-0300",
    externalRefs: ["sf-009999", "hs-111", "custom-ent-001"],
    totalCalls: 12,
    lastCallAt: "2024-01-15T15:00:00Z",
    createdAt: "2023-03-01T00:00:00Z",
    updatedAt: "2024-01-15T15:00:00Z",
  },
]

// ==================== MOCK FRAMEWORKS ====================

export const mockFrameworks: Framework[] = [
  {
    id: "fw-1",
    name: "MEDDIC",
    description:
      "Metrics, Economic Buyer, Decision Criteria, Decision Process, Identify Pain, Champion - A comprehensive B2B sales qualification framework.",
    source: "template",
    activeVersionId: "fwv-1",
    versions: [
      {
        id: "fwv-1",
        frameworkId: "fw-1",
        versionNumber: 2,
        phases: [
          {
            id: "ph-1",
            name: "Metrics",
            objective: "Quantify the business impact and ROI",
            rubric: "Rep should uncover specific metrics the prospect uses to measure success",
            order: 1,
            questions: [
              {
                id: "q-m1",
                text: "What metrics do you use to measure success?",
                weight: 2,
                tags: ["discovery"],
                required: true,
                order: 1,
              },
              {
                id: "q-m2",
                text: "What is the current cost of the problem?",
                weight: 3,
                tags: ["discovery", "pain"],
                required: true,
                order: 2,
              },
              {
                id: "q-m3",
                text: "What ROI do you expect from a solution?",
                weight: 2,
                tags: ["value"],
                required: false,
                order: 3,
              },
              {
                id: "q-m4",
                text: "How will you measure the success of this project?",
                weight: 2,
                tags: ["value"],
                required: true,
                order: 4,
              },
            ],
            battleCards: [
              {
                id: "bc-1",
                title: "ROI Objection",
                trigger: "When prospect questions the value",
                response: "Let me walk you through our ROI calculator with similar customers...",
                tags: ["objection", "value"],
              },
            ],
          },
          {
            id: "ph-2",
            name: "Economic Buyer",
            objective: "Identify the person with budget authority",
            rubric: "Rep should identify who controls the budget and understand the approval process",
            order: 2,
            questions: [
              {
                id: "q-e1",
                text: "Who has final budget approval?",
                weight: 3,
                tags: ["qualification"],
                required: true,
                order: 1,
              },
              {
                id: "q-e2",
                text: "What is the budget range?",
                weight: 2,
                tags: ["qualification"],
                required: true,
                order: 2,
              },
              {
                id: "q-e3",
                text: "Have funds been allocated for this project?",
                weight: 2,
                tags: ["qualification"],
                required: false,
                order: 3,
              },
              {
                id: "q-e4",
                text: "What is the procurement process?",
                weight: 1,
                tags: ["process"],
                required: false,
                order: 4,
              },
            ],
            battleCards: [],
          },
          {
            id: "ph-3",
            name: "Decision Criteria",
            objective: "Understand what factors will influence the decision",
            rubric: "Rep should uncover technical, business, and personal decision criteria",
            order: 3,
            questions: [
              {
                id: "q-d1",
                text: "What are your must-have requirements?",
                weight: 3,
                tags: ["requirements"],
                required: true,
                order: 1,
              },
              {
                id: "q-d2",
                text: "What would make this project a failure?",
                weight: 2,
                tags: ["requirements"],
                required: false,
                order: 2,
              },
              {
                id: "q-d3",
                text: "How will you evaluate different solutions?",
                weight: 2,
                tags: ["process"],
                required: true,
                order: 3,
              },
              {
                id: "q-d4",
                text: "What integrations are required?",
                weight: 1,
                tags: ["technical"],
                required: false,
                order: 4,
              },
            ],
            battleCards: [],
          },
          {
            id: "ph-4",
            name: "Decision Process",
            objective: "Map out the buying process and timeline",
            rubric: "Rep should understand all stakeholders, steps, and timeline",
            order: 4,
            questions: [
              {
                id: "q-p1",
                text: "What is your decision timeline?",
                weight: 3,
                tags: ["timeline"],
                required: true,
                order: 1,
              },
              {
                id: "q-p2",
                text: "Who else needs to be involved in this decision?",
                weight: 3,
                tags: ["stakeholders"],
                required: true,
                order: 2,
              },
              {
                id: "q-p3",
                text: "What steps are required before you can sign?",
                weight: 2,
                tags: ["process"],
                required: true,
                order: 3,
              },
              {
                id: "q-p4",
                text: "Are there any legal or security reviews required?",
                weight: 1,
                tags: ["process"],
                required: false,
                order: 4,
              },
              {
                id: "q-p5",
                text: "Have you purchased similar solutions before?",
                weight: 1,
                tags: ["process"],
                required: false,
                order: 5,
              },
            ],
            battleCards: [],
          },
          {
            id: "ph-5",
            name: "Identify Pain",
            objective: "Deeply understand the prospect's pain points",
            rubric: "Rep should uncover the root cause and business impact of pain",
            order: 5,
            questions: [
              {
                id: "q-i1",
                text: "What is the biggest challenge you're facing?",
                weight: 3,
                tags: ["pain", "discovery"],
                required: true,
                order: 1,
              },
              {
                id: "q-i2",
                text: "How long have you had this problem?",
                weight: 2,
                tags: ["pain"],
                required: true,
                order: 2,
              },
              {
                id: "q-i3",
                text: "What happens if you don't solve this?",
                weight: 3,
                tags: ["pain", "urgency"],
                required: true,
                order: 3,
              },
              {
                id: "q-i4",
                text: "What have you tried before?",
                weight: 2,
                tags: ["pain", "competition"],
                required: true,
                order: 4,
              },
            ],
            battleCards: [
              {
                id: "bc-2",
                title: "Status Quo Objection",
                trigger: "When prospect wants to do nothing",
                response:
                  "I understand. Let me share what other customers in your situation experienced when they delayed...",
                tags: ["objection", "urgency"],
              },
            ],
          },
          {
            id: "ph-6",
            name: "Champion",
            objective: "Identify and develop an internal advocate",
            rubric: "Rep should find someone who will sell internally for you",
            order: 6,
            questions: [
              {
                id: "q-c1",
                text: "Who will advocate internally for us?",
                weight: 3,
                tags: ["champion"],
                required: true,
                order: 1,
              },
              {
                id: "q-c2",
                text: "What would make you a hero internally?",
                weight: 2,
                tags: ["champion", "value"],
                required: true,
                order: 2,
              },
              {
                id: "q-c3",
                text: "Can you introduce me to other stakeholders?",
                weight: 2,
                tags: ["champion", "access"],
                required: false,
                order: 3,
              },
            ],
            battleCards: [],
          },
        ],
        isActive: true,
        isDraft: false,
        createdAt: "2024-01-01T00:00:00Z",
        createdBy: "John Smith",
        publishedAt: "2024-01-01T00:00:00Z",
      },
    ],
    usageCount: 45,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "fw-2",
    name: "SPIN Selling",
    description:
      "Situation, Problem, Implication, Need-Payoff - A consultative selling framework focused on asking the right questions.",
    source: "template",
    activeVersionId: "fwv-2",
    versions: [
      {
        id: "fwv-2",
        frameworkId: "fw-2",
        versionNumber: 1,
        phases: [
          {
            id: "ph-s1",
            name: "Situation",
            objective: "Understand the prospect's current situation",
            rubric: "Gather facts about the prospect's existing setup",
            order: 1,
            questions: [
              {
                id: "q-s1",
                text: "Tell me about your current process",
                weight: 2,
                tags: ["discovery"],
                required: true,
                order: 1,
              },
              {
                id: "q-s2",
                text: "What tools do you currently use?",
                weight: 1,
                tags: ["discovery"],
                required: false,
                order: 2,
              },
            ],
            battleCards: [],
          },
          {
            id: "ph-s2",
            name: "Problem",
            objective: "Uncover problems and difficulties",
            rubric: "Help prospect articulate their challenges",
            order: 2,
            questions: [
              {
                id: "q-sp1",
                text: "What challenges are you facing?",
                weight: 3,
                tags: ["pain"],
                required: true,
                order: 1,
              },
              { id: "q-sp2", text: "Where do things break down?", weight: 2, tags: ["pain"], required: true, order: 2 },
            ],
            battleCards: [],
          },
        ],
        isActive: true,
        isDraft: false,
        createdAt: "2024-01-05T00:00:00Z",
        createdBy: "John Smith",
        publishedAt: "2024-01-05T00:00:00Z",
      },
    ],
    usageCount: 28,
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-01-05T00:00:00Z",
  },
  {
    id: "fw-3",
    name: "Custom Discovery Framework",
    description: "Our internal discovery framework tailored to our product and market.",
    source: "custom",
    activeVersionId: "fwv-3",
    versions: [
      {
        id: "fwv-3",
        frameworkId: "fw-3",
        versionNumber: 3,
        phases: [
          {
            id: "ph-c1",
            name: "Introduction",
            objective: "Build rapport and set agenda",
            rubric: "Establish trust and clarify meeting goals",
            order: 1,
            questions: [
              {
                id: "q-c1",
                text: "What prompted you to take this meeting?",
                weight: 2,
                tags: ["intro"],
                required: true,
                order: 1,
              },
            ],
            battleCards: [],
          },
        ],
        isActive: true,
        isDraft: false,
        createdAt: "2024-01-08T00:00:00Z",
        createdBy: "Admin",
        publishedAt: "2024-01-08T00:00:00Z",
      },
    ],
    usageCount: 12,
    createdAt: "2023-12-01T00:00:00Z",
    updatedAt: "2024-01-08T00:00:00Z",
  },
]

// ==================== MOCK FRAMEWORK TEMPLATES ====================

export const mockFrameworkTemplates: FrameworkTemplate[] = [
  {
    id: "tpl-1",
    name: "BANT",
    description: "Budget, Authority, Need, Timeline - Classic qualification framework",
    category: "popular",
    previewPhases: ["Budget", "Authority", "Need", "Timeline"],
    isLicensed: false,
    phaseCount: 4,
    questionCount: 16,
  },
  {
    id: "tpl-2",
    name: "Challenger Sale",
    description: "Teach, Tailor, Take Control - Push prospects out of their comfort zone",
    category: "popular",
    previewPhases: ["Warmer", "Reframe", "Rational Drowning", "Emotional Impact", "A New Way", "Your Solution"],
    isLicensed: true,
    phaseCount: 6,
    questionCount: 24,
  },
  {
    id: "tpl-3",
    name: "GPCTBA/C&I",
    description: "Goals, Plans, Challenges, Timeline, Budget, Authority, Consequences & Implications",
    category: "qualification",
    previewPhases: ["Goals", "Plans", "Challenges", "Timeline", "Budget", "Authority", "Consequences", "Implications"],
    isLicensed: false,
    phaseCount: 8,
    questionCount: 32,
  },
  {
    id: "tpl-4",
    name: "Value Selling",
    description: "Focus on business value and ROI throughout the sales process",
    category: "methodology",
    previewPhases: ["Discover", "Qualify", "Develop", "Prove", "Close"],
    isLicensed: true,
    phaseCount: 5,
    questionCount: 20,
  },
]

// ==================== MOCK INTEGRATIONS ====================

export const mockApiKeys: IntegrationApiKey[] = [
  {
    id: "key-1",
    name: "Production API Key",
    keyPreview: "...x7k9",
    scopes: ["calls:read", "calls:write", "frameworks:read"],
    createdAt: "2024-01-01T00:00:00Z",
    lastUsedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "key-2",
    name: "CRM Integration",
    keyPreview: "...m3n4",
    scopes: ["calls:read", "clients:read"],
    createdAt: "2024-01-05T00:00:00Z",
    lastUsedAt: "2024-01-14T22:00:00Z",
  },
]

export const mockWebhookSubscriptions: WebhookSubscription[] = [
  {
    id: "wh-1",
    url: "https://api.example.com/webhooks/maxout",
    events: ["call.completed", "call.analyzed"],
    secret: "whsec_abc123...",
    isActive: true,
    lastDeliveryAt: "2024-01-15T11:05:00Z",
    lastDeliveryStatus: "success",
    createdAt: "2024-01-02T00:00:00Z",
  },
  {
    id: "wh-2",
    url: "https://hooks.slack.com/services/xxx",
    events: ["call.failed"],
    secret: "whsec_def456...",
    isActive: true,
    lastDeliveryAt: "2024-01-14T12:00:00Z",
    lastDeliveryStatus: "failed",
    createdAt: "2024-01-10T00:00:00Z",
  },
]

// ==================== MOCK ADMIN DATA ====================

export const mockWebhookEvents: WebhookEvent[] = [
  {
    id: "evt-1",
    subscriptionId: "wh-1",
    eventType: "call.completed",
    payload: { callId: "call-1", status: "ready" },
    status: "delivered",
    attempts: 1,
    deliveredAt: "2024-01-15T11:05:00Z",
    createdAt: "2024-01-15T11:05:00Z",
  },
  {
    id: "evt-2",
    subscriptionId: "wh-2",
    eventType: "call.failed",
    payload: { callId: "call-4", error: "Bot not admitted" },
    status: "failed",
    attempts: 3,
    lastAttemptAt: "2024-01-14T12:30:00Z",
    error: "Connection timeout",
    createdAt: "2024-01-14T12:00:00Z",
  },
  {
    id: "evt-3",
    subscriptionId: "wh-1",
    eventType: "call.analyzed",
    payload: { callId: "call-1", frameworkId: "fw-1", score: 78 },
    status: "delivered",
    attempts: 1,
    deliveredAt: "2024-01-15T11:10:00Z",
    createdAt: "2024-01-15T11:10:00Z",
  },
]

export const mockJobAttempts: JobAttempt[] = [
  {
    id: "job-1",
    jobType: "finalize_recording",
    entityId: "call-1",
    entityType: "call",
    status: "completed",
    attempts: 1,
    startedAt: "2024-01-15T10:48:00Z",
    completedAt: "2024-01-15T11:05:00Z",
    createdAt: "2024-01-15T10:48:00Z",
  },
  {
    id: "job-2",
    jobType: "run_analysis",
    entityId: "call-1",
    entityType: "call",
    status: "completed",
    attempts: 1,
    startedAt: "2024-01-15T11:00:00Z",
    completedAt: "2024-01-15T11:08:00Z",
    createdAt: "2024-01-15T11:00:00Z",
  },
  {
    id: "job-3",
    jobType: "finalize_recording",
    entityId: "call-4",
    entityType: "call",
    status: "failed",
    attempts: 3,
    lastError: "Bot was not admitted to meeting",
    startedAt: "2024-01-14T11:47:00Z",
    createdAt: "2024-01-14T11:47:00Z",
  },
  {
    id: "job-4",
    jobType: "finalize_recording",
    entityId: "call-2",
    entityType: "call",
    status: "running",
    attempts: 1,
    startedAt: "2024-01-16T15:00:00Z",
    createdAt: "2024-01-16T15:00:00Z",
  },
]

export const mockStorageUsage: StorageUsage = {
  totalBytes: 2500000000,
  videoBytes: 2200000000,
  audioBytes: 150000000,
  transcriptBytes: 50000000,
  otherBytes: 100000000,
  callCount: 45,
}

// ==================== MOCK ORGANIZATION ====================

export const mockOrganization: Organization = {
  id: "org-1",
  name: "Sales Team Inc",
  slug: "sales-team",
  retentionDays: 90,
  members: [
    {
      id: "mem-1",
      name: "John Smith",
      email: "john@company.com",
      role: "owner",
      joinedAt: "2023-01-01T00:00:00Z",
      lastActiveAt: "2024-01-15T10:00:00Z",
    },
    {
      id: "mem-2",
      name: "Jane Doe",
      email: "jane@company.com",
      role: "admin",
      joinedAt: "2023-03-01T00:00:00Z",
      lastActiveAt: "2024-01-14T15:00:00Z",
    },
    {
      id: "mem-3",
      name: "Bob Wilson",
      email: "bob@company.com",
      role: "member",
      joinedAt: "2023-06-01T00:00:00Z",
      lastActiveAt: "2024-01-10T09:00:00Z",
    },
  ],
  createdAt: "2023-01-01T00:00:00Z",
}

export const mockOrgCapabilities: OrgCapabilities = {
  v1Features: {
    callLibrary: true,
    frameworks: true,
    integrations: true,
    embeds: true,
  },
  v2Features: {
    liveCoach: false,
    contentStudio: false,
    whiteLabel: false,
  },
  limits: {
    maxCalls: 1000,
    maxFrameworks: 20,
    maxApiKeys: 10,
    maxWebhooks: 5,
  },
}
